apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapplication
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jyang49/argocd1.git
    targetRevision: HEAD
    path: examples/10_deployment/
  destination:
    server: https://kubernetes.default.svc
    namespace: testing2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
