apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: yaml-02-pod
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: examples/yaml/02-pod/manifest
    repoURL: "https://github.com/jyang49/argocd.git"
    targetRevision: main
  syncPolicy:
    automated: {}
