apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-02-simple
  namespace: argocd
spec: 
  destination: 
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: examples/helm/02-simple/manifest
    repoURL: "https://github.com/jyang49/argocd.git"
    targetRevision: main
